### ISSUE TITLE
Ether Spider + Collar of Subordination Bug

### ISSUE THREAD

**Issue by neffmallon** [jeremylarner/keyteki#104]
What happened:
Player 1 has Ether Spider in play, it has captured 10 amber.
Player 2 plays Collar of Subordination on Ether Spider, causing it to switch sides.
Player 1 earns an amber, adding to to Ether Spider.
Player 2 kills off Ether Spider via fighting. All the amber mistakenly goes to Player 1, even though 10 of the amber should go to Player 2 since it was their amber that was captured.

**Comment by jeremylarner** [comment]
Amber always goes to the opposing player, so in this case Player 1 should get 11 amber when Ether Spider dies.  Taking control of a creature with amber on it is generally a bad idea

**Comment by neffmallon** [comment]
yup, sorry! you are right, this isn't a bug!
