### ISSUE TITLE
Typo in play text of Positron Bolt

### ISSUE THREAD

**Issue by dividedpixel** [jeremylarner/keyteki#105]
There is a typo in the play text of Positron Bolt, with the second instance of damage spelled 'damange' instead. Quote and screenshot as follows:

> BigPopp uses Positron Bolt to deal 3 damage to Dr. Escotera, 2 _damange_ to Harland Mindlock and 1 damage to Dodger

![image](https://user-images.githubusercontent.com/12380351/49534844-4a18f800-f8cb-11e8-897e-e14717f9e2d4.png)

**Comment by jeremylarner** [comment]
This should be fixed now
