### ISSUE TITLE
Wild Wormhole Doesn't Play Top Card If Deck Is Empty

### ISSUE THREAD

**Issue by polluxpolaris** [jeremylarner/keyteki#109]
1. Make sure deck shows "Draw (0)"
2. Play Wild Wormhole
3. You get the aember but card ability does not resolve

Expected behavior would be to shuffle the deck and then play the top card as usual.

This bug may possibly have also caused issue#8

**Comment by jeremylarner** [comment]
You only reshuffle your deck when you are instructed to draw a card and your deck is empty.  WW doesn't mention drawing a card, so it will not cause your deck to be reshuffled
