### ISSUE TITLE
Mushroom Man

### ISSUE THREAD

**Issue by TheBrianFactor** [jeremylarner/keyteki#115]
Mushroom Man does not properly increase his power no matter the number of unforged keys that the player has.  Whether it's 3, 2, or 1, Mushroom Man never receives +1 Power markers and is always treated as having his base power.

**Comment by Eric-Fletcher** [comment]
Constant abilities don't add power counters.

Did you confirm that it was treating it as a 2 power creature? My use has seen it treated correctly.
