### ISSUE TITLE
Niffle Queen's Text is ignored

### ISSUE THREAD

**Issue by Poledouris** [jeremylarner/keyteki#118]
The text on the Niffle Queen card is as follows:

Each other friendly Beast creature gets +1 power. Each other friendly Niffle creature gets +1 power.

I just played a game with this card and no other beasts got this power boost.

I was using this deck:

https://keyforge-compendium.com/decks/7d35657a-3c98-4282-a527-ea971be73041

And I had 2 Niffle Apes out, and a Briar Grubbling out while the Niffle Queen was also on the board. The Grubbling should have gotten +1, and I believe the Niffle Apes should have gotten +2 (I could be wrong, but this makes sense considering the Niffle Apes satisfy both conditions of the text).

Love the site so far, great for testing out new decks when no one else is available to play live!

Here is the final board:

![image](https://user-images.githubusercontent.com/25989567/49756875-04707c80-fc89-11e8-82b8-1284c1a262f5.png)

**Comment by Poledouris** [comment]
Good catch! Then the bug is that the +power tokens aren’t being shown.

**Comment by Eric-Fletcher** [comment]
Constant abilities don't add power tokens, they just modify the effective power of the creatures.

**Comment by Poledouris** [comment]
So there is no visual clue that the power has increased, that seems flawed? Playing outside of the site, you would put a +power card on each of those creatures. Why wouldn't that be the same in this case? Just a way for both players to be aware of the extra power.

For example, I'm sure the opponent did 2 damage to the Grubbling thinking that would kill it, and when it didn't, he was probably confused and thought something was broken. Just as I thought something was broken because the Power on the cards didn't change.
