### ISSUE TITLE
Stealer of Souls

### ISSUE THREAD

**Issue by TheBrianFactor** [jeremylarner/keyteki#119]
When Stealer of Souls destroys any creature while fighting they are not purged as they should be.  This is a crucial mechanic in a few of my decks, please fix this ASAP!  Stealer of Souls does not need to survive the fight as his effect is persistent that if any creature is destroyed while fighting Stealer of Souls, it is purged and I gain 1 amber.

**Comment by skrohmagnon** [comment]
it's false. Like every constant ability, the creature must survive to the fight to apply is effect.
rules book p10, fight :
 _If either creature in a fight has a constant ability referencing the end of the fight (example: “after an enemy creature is destroyed fighting this creature...”), the creature must survive the fight to resolve the ability_
