### ISSUE TITLE
Biomatrix Backup not working

### ISSUE THREAD

**Issue by Grizzbear111** [jeremylarner/keyteki#121]
When I put Biomatrix Backup on my own creature, and my opponent destroys the creature (either kills in battle or uses an effect to destroy) it is sending the creature to my discard pile and not my archives. Happened yesterday in 3 different games. Shouldn't I get the choice as its my creature?

**Comment by Rodigee** [comment]
Biomatrix is a "may" ability so the active player, your opponent who is currently taking his or her turn, decides whether to active Biomatrix Backup.

**Comment by ReubenMH** [comment]
I just encountered this bug too. Looking at the response, there's no way that the opponent gets to decide whether I should put it in my archives or not, or it becomes a useless card.
