### ISSUE TITLE
Remote Access Bug

### ISSUE THREAD

**Issue by wistro** [jeremylarner/keyteki#124]
Remote Access/Nexus etc doesn't allow me to use an opponent's artifact that would have no effect. I should still be able to use it and exhaust it without it doing anything to stop my opponent from using it the next turn.

**Comment by scrowner** [comment]
Nexus does not work. Reaped with it and opponent had two Sanctum and one Shadow artifact. The Shadow artifact was a global and the two Sanctum were Action and Omni.
