### ISSUE TITLE
Free æmber!?

### ISSUE THREAD

**Issue by chaoticserenitea** [jeremylarner/keyteki#129]
I was in a game where the opponent switched to manual and just gave themselves 19+ Æmber.
![7edbcba5-2edb-400f-9cd1-a65445645629](https://user-images.githubusercontent.com/45734587/50044670-00f83f00-0055-11e9-9353-3bf45342abb4.jpeg)

Is there no way to limit what can be added in manual? 
Or any way to report a player when they are doing something like this?

**Comment by ejlertson** [comment]
Only thing you can do about it atm is to tell him that he is an idiot and then add him to your Blocked Players list

**Comment by chaoticserenitea** [comment]
> Only thing you can do about it atm is to tell him that he is an idiot and then add him to your Blocked Players list

Lmao. Yeah, I blocked the player already.
