### ISSUE TITLE
Brobnar Gaunlet of Command not working correctly

### ISSUE THREAD

**Issue by SeekerHI** [jeremylarner/keyteki#134]
When someone uses Gaunlet of Command they are using it to reap. When they should only be able fight

**Comment by ejlertson** [comment]
IF yo have no creature out for them to fight against, they can ready the creature and then reap instead.
ITs in the the rules. You do as much as possible, in this case Ready. Then when you cant fight anyone you just have a a Ready creature, and if its a Brobnar turn you can reap with it :)

So no bug and WAI :)

**Comment by SeekerHI** [comment]
I had multiple creatures out for the other player to fight though.

**Comment by ejlertson** [comment]
Sounds weird.
Was there some other reason he could not fight?  Was Fogify used for excample?

I havent had it happen with Anger/Gauntlet of Command unless there was no creature to fight

**Comment by SeekerHI** [comment]
Not sure. Played another game with gauntlet on my side and it worked correctly. I’ll keep an eye out for other cards played to see. But no worries right now.
