### ISSUE TITLE
Zyzzix the Many Fight/Reap Trigger

### ISSUE THREAD

**Issue by croket0902** [jeremylarner/keyteki#14]
Zyzzix the Many only trigger Reap ability, it can't trigger its Fight ability.

Zyzzix ability: Fight/Reap: Reveal a creature from your hand . If you do archive it and add three +1 power counter the Zyzzix the Many.

**Comment by Eric-Fletcher** [comment]
Are you sure? Fight abilities only happen after the fight & damage have resolved, and it works correctly for me.

**Comment by myrrien** [comment]
the fight ability activates only if the creature survives the combat, so if Zyzzix receives an amount of damage equal to its power before adding 3 for the ability it dies and the ability does not activate
