### ISSUE TITLE
Wishlist: Remove information about what card they are about to play until they actually play it

### ISSUE THREAD

**Issue by splut** [jeremylarner/keyteki#140]
Selecting a card shows the opponent the card you have, even if you then click cancel. Hide this information from the opponent until they can no longer cancel the cast/ability as it gives the opponent information about your hand that they shouldn't have, very relevant if you decide not to cast something and hold it for a couple of turns. Knowing my opponent has certain cards makes them have less value for my opponent

**Comment by ejlertson** [comment]
The easy fix would be on the user end. 
Dont click the card unless you are sure you want to use it. Really not an issue that required codework-dedication.

**Comment by splut** [comment]
Not all users will realise that this is something that is happening. They are giving away information to their 
opponents that they shouldn't be. If in paper I was looking at my hand and making a decision about a card it isn't announced, so why should it be on TheCrucible? Just wanting a more truthful representation of the game.
