### ISSUE TITLE
Wild Wormhole

### ISSUE THREAD

**Issue by Rognetudjiu** [jeremylarner/keyteki#155]
The rules specify that if the top card of our deck draw by wild wormhole is not playable it should return to the top of our deck, not go in our discard pile. I have draw Hand of Dis with no creature not on a side, it should have returned to the top of my deck but it end up discarded. Same with some upgrade with no creature in play. 
Thanks for making it possible to play KeyForge online ! :-)

**Comment by bearthegrudge** [comment]
You can play Hand of Dis without a flank creature, it just does nothing.

**Comment by Rognetudjiu** [comment]
Ok, sorry! 😅 Thanks for the answer!
