### ISSUE TITLE
House Selection

### ISSUE THREAD

**Issue by Bozobarnum** [jeremylarner/keyteki#157]
Pretty please make it so you can undo house selection, as long as you haven't played any cards.  I've lost two games because I mis-clicked which I realize is my fault, but it would be really nice to be able to change the house after selecting.

TheCrucible is amazing.  Thank you for making it!!!

**Comment by ejlertson** [comment]
It already exists:
/active-house x - Change your active house to x

**Comment by Bozobarnum** [comment]
Omg thank you!!! Is there a list somewhere of commands like that?
