### ISSUE TITLE
Neutron Shark implementation

### ISSUE THREAD

**Issue by jaimefps** [jeremylarner/keyteki#158]
I see that a previous ticket mentions this issue https://github.com/jeremylarner/keyteki/issues/17

But I am under the impression that Neutron Shark's effect should continue occurring even if Neutron Shark destroys itself. (Currently the webapp stops Shark's effect when it destroys itself).

**Comment by bearthegrudge** [comment]
You are incorrect. As soon as the shark (or any creature) dies they can no longer trigger abilities.

**Comment by jaimefps** [comment]
So the ability does not exist apart from the creature itself?
I was under the impression that once the ability is triggered, it is not tied to the creature that induced the chain effect to execute. The base condition for the recursion process (as described by the ability) only seems to check whether a Logos card has been discarded, not whether Shark is still in play.

**Comment by jaimefps** [comment]
Wow, ok, awesome. That makes Shark even more powerful than I thought!
Thanks for looking that up and sharing. I'll close the ticket.
