### ISSUE TITLE
Urchin and Autocannon

### ISSUE THREAD

**Issue by AdamPhilpotMDX** [jeremylarner/keyteki#159]
This still works incorrectly, as Urchin enters and does not steal the aember.  Additionally, a choice of timing is not offered.

Thanks!

**Comment by UltimoFox** [comment]
I'm not sure how this is supposed to work. Urchin is destroyed before its Play ability is resolved? If so, why is that? In order of play rules the stealing and damage occur at the same time, so i'm not sure which is supposed to be right.
