### ISSUE TITLE
Nexus can't use Ritual of Balance, and it should be able to

### ISSUE THREAD

**Issue by ira212** [jeremylarner/keyteki#164]
Steps to reproduce:
1) Opponent has Ritual of Balance and fewer than 6 amber.
2) On your turn, reap with Nexus.

Notice that Ritual of Balance can't be used.

Intended behavior:
Ritual of Balance should be able to be used, though if it is, there wouldn't be any effect (other than exhausting Ritual of Balance). The "Action:" text doesn't prohibit the card from being used, it merely states a conditional for an effect.

Note: Nexus + Ritual of Balance does work properly if the opponent has 6+ amber.

Note 2: I wonder if Ritual of Balance can't be used on your own turn while your opponent has 6 or fewer amber. (Though I really can't think of any reason at all why you'd want to do that, other than stalling.)

**Comment by anoda9** [comment]
Similar interaction with Remote Access is also bugged.
