### ISSUE TITLE
Twin Bolt Emission - Double faction: Logos + Shadows

### ISSUE THREAD

**Issue by 7razcal7** [jeremylarner/keyteki#170]
I have Twin Bolt Emission in a deck and as far as I know it is a Logos card.

Today I saw someone play the card and it had a Logos faction in top left corner and Shadows faction in top right corner and was therefore able to play it during a Shadows turn. This should not be possible?

[I did not write down the deck or username]

**Comment by splut** [comment]
I suspect this was a maverick version of the card and is in the shadows portion of the deck.

**Comment by skrohmagnon** [comment]
it's a maverick card. it's suprising but normal.

**Comment by 7razcal7** [comment]
Thx!
