### ISSUE TITLE
Problems with Arise and Key Hammer

### ISSUE THREAD

**Issue by histeria1978** [jeremylarner/keyteki#172]
I have watched two mistakes with my cards:

- Arise. When I use it I can choose Brobnar, Dis and Logos but my deck has not Logos but Sanctum.

- Key Hammer: even if my opponent did not forge a key on his last turn, he gets 6 aembar.

**Comment by Rodigee** [comment]
Key Hammer is working as intended, the 6 aember is not conditional.
