### ISSUE TITLE
Zyzzix the Many

### ISSUE THREAD

**Issue by misakimi** [jeremylarner/keyteki#180]
Just tried to use Zyzzix twice in a game to add 3 counters on but both times it didn't let me reveal a creature from my hand. On both occasions it should have done. I didn't have Mars creatures but it doesn't state it must be a Mars creature.
A box came up saying about triggered abilities but it didn't seem to let me reveal still. Any ideas?

**Comment by jeremylarner** [comment]
Zyzzix the Many is highlighted and clickable for me
