### ISSUE TITLE
Overlord Greking ability did not work

### ISSUE THREAD

**Issue by Saxmaam** [jeremylarner/keyteki#182]
text: Overlord Greking
After an enemy creature is destroyed fighting Overlord Greking, put that creature into play under your control.

Twice in one game, this did not happen.  My opponent agreed this was incorrect.

**Comment by Rodigee** [comment]
Was Overlord Greking also destroyed in the fight?

**Comment by xjoaniex** [comment]
I had this happen to me tonight as well:

Playing earlier I fought with Overlord Grekin, beat Dextre, survived the fight but Dextre did not come into my control like it should have
