### ISSUE TITLE
Can't see games I've joined or created

### ISSUE THREAD

**Issue by santamuri** [jeremylarner/keyteki#187]
When I start or join a game it seems like the game starts but then the site cuts back the game list. if I F5 I can see the game but the second I attempt to interact with the game it boots back to the game list. I can even see a bunch of disconnects and reconnects when i do get into the game but the second I try to chat or click anything it boots me back out.

**Comment by jeremylarner** [comment]
Maybe try a different browser?

**Comment by santamuri** [comment]
Started working. I think it still thought I was in a different game and
kept knocking me out. Working now but will message if it does it again.
Great site though! Glad to be able to play between sealed events.
