### ISSUE TITLE
Improvement: Lobby for net decks

### ISSUE THREAD

**Issue by adamnd1** [jeremylarner/keyteki#188]
I'm sure you're finding it difficult to police the many net decks being used on the site. My suspicion is that most (but obviously not all) of the people using these aren't so much looking to steamroll people in casual lobby, but are genuinely curious about how some of these super-rare decks perform in practice. So I'd recommend a new lobby that actually encourages use of net decks or other very powerful decks; one of the great things about the site is the ability to use decks you don't (and probably never will) own, so why not lean into it?

Thanks for reading!

**Comment by jeremylarner** [comment]
I don't really want to encourage netdecking

**Comment by adamnd1** [comment]
Fair enough, thanks for the reply and all your hard work!
