### ISSUE TITLE
possible new issue for 'ready and fight'

### ISSUE THREAD

**Issue by jroc83** [jeremylarner/keyteki#190]
I submitted a bug yesterday related to "ready and fight" (https://github.com/jeremylarner/keyteki/issues/184)

...but I was mistaken and another community member helped me test...and I closed my ticket.

...however, today there was an update and now whenever an effect says "ready and fight", if there are no opposing creatures, the ready action doesn't happen.

---------------

...because this is a new game and we are all learning the rules, my original bug was due to me not understanding how "do as much as you can" worked, when no other creatures were on board.

...unless I (we) are/am wrong about that now...and you only have the option of fighting with "ready and fight" and reap is not allowed...even then, it should still ready & just not be allowed to reap. though there was a lot of confidence in the forum that reaping off of a ready was fine, provided that the creature was of the selected house (as per "do as much as you can")

----------------------

Sorry in advance for the issues that I was reporting (potential false positive) yesterday.

**Comment by CasMat9** [comment]
I have also seen this bug. What I saw was that, when using the ready and fight effects (Anger, Gauntlet of Command, etc.), if there is nothing to fight the creature is immediately exhausted. The log records it as "[player] uses [creature]." No amber is generated from this.
