### ISSUE TITLE
Forgot Password reCAPTCHA error

### ISSUE THREAD

**Issue by MxIllusionment** [jeremylarner/keyteki#2]
The reCAPTCHA verification for the Forgot Password page is displaying "ERROR for site owner:
Invalid domain for site key".

**Comment by jeremylarner** [comment]
The captcha isn't working at the moment.  If you've forgotten your password and you'd like me to remove your account so you can recreate it, please contact me by PM on the discord

**Comment by jeremylarner** [comment]
This should be fixed now
