### ISSUE TITLE
A creature that provide skirmish to neighbor

### ISSUE THREAD

**Issue by rohithrpai** [jeremylarner/keyteki#217]
Untamed creature Halacor ability to provide skirmish to it's neighboring creature is not working 

![image](https://user-images.githubusercontent.com/25734068/51081517-590b7b00-16bf-11e9-8c85-272b9caf99b4.png)

**Comment by splut** [comment]
It gives skirmish to creatures on the flanks (end of line) not necessarily its neighbour. Was the creature you expected to have skirmish on the flank?
