### ISSUE TITLE
The Warchest doesn't make aember

### ISSUE THREAD

**Issue by Nat-Faeeria** [jeremylarner/keyteki#228]
Though I used the warchest at the beginning of the turn and destroyed creatures, I didn't get any aember. It happened all the time I used it.

**Comment by batmanbury** [comment]
@Nat-Faeeria Oops! Because you're using it wrong. You need to activate it AFTER you've finished fighting:

![](http://aembertree.com/cards/core-027.jpg)

**Comment by Sajuro** [comment]
oh activate after fight noted
