### ISSUE TITLE
Wild Wormhole the first turn

### ISSUE THREAD

**Issue by McGiogen** [jeremylarner/keyteki#244]
Wild Wormhole used the first turn do nothing, while turn 1 rule only applies to cards played from your hand. Wild Wormhole would resolve as normal.

Source: https://www.reddit.com/r/KeyforgeGame/comments/9xx1eq/first_turn_wild_wormhole/

**Comment by G0dr1c** [comment]
What card did it try to play from the top of your deck?  It could have been an invalid card (like Truebaru for example).  Do you have a screenshot of the incident?  Did it tell you what card it tried to play? It normally does.

**Comment by McGiogen** [comment]
No, it didn't tell me what card it tried to play, that's why I reported. Sorry but I don't have the screenshot.

**Comment by Jarimy123** [comment]
It probably tried to play an illegal card - like Kalifi Dragon - or something.  If that happens it goes back to top of your deck.  It's definitely not bugged so delete this post.

**Comment by McGiogen** [comment]
Closing. I will retry to play Wild Wormhole in the first turn as soon as possible.
