### ISSUE TITLE
Armageddon Cloak does not kill creature after taking full damage second time. 

### ISSUE THREAD

**Issue by jtrevag** [jeremylarner/keyteki#25]
**Armageddon Cloak** 
(House) Sanctum. 
Upgrade. 
1 Aember. 
Text: This creature gains Hazardous 2 and, "Destroyed: Fully heal this creature and destroy Armageddon cloak instead"

Expected Behavior: Creature takes full damage first time, Armageddon Cloak is destroyed, Creature takes full damage second time, creature is removed from game.

Current Behavior: Creature takes full damage first time, Armageddon Cloak is destroyed, Creature can take any amount of damage and cannot be removed from the game. (Except using manual mode).

**Comment by jeremylarner** [comment]
This should be fixed now - thanks for the detailed bug report!
