### ISSUE TITLE
Key Hammer with no ambar or keys

### ISSUE THREAD

**Issue by TheLeiro** [jeremylarner/keyteki#252]

**Comment by TheLeiro** [comment]
I once used the Key Hammer on the first turn and gave us both a apparently random amount of ambar.

**Comment by blinkingline** [comment]
Key Hammer on first turn should provide your opponent with 6 Æmber and you with 1.

**Comment by TheLeiro** [comment]
True, I interpreted that it would only give the other player 6 âmbër IF he had forged a key the previous turn.
My bad, sorry.
