### ISSUE TITLE
Mating Season

### ISSUE THREAD

**Issue by Bolfry** [jeremylarner/keyteki#27]
When Mating Season was played it put the creature in the deck but did not render any amber.  Also, it made adjusting amber manually no longer function as well as getting amber in any way.

Also, there needs to be Power Counter options for some creatures - there is no option to add them.  Please see Zyzzix the Many.  He sends a creature to archives and gets 3 power counters for a fight/reap action.

**Comment by jeremylarner** [comment]
This should be fixed now
