### ISSUE TITLE
"Ready and Fight" or Otherwise Attempting to Fight with a Stunned Creature Should Remove Stun

### ISSUE THREAD

**Issue by tsilver33** [jeremylarner/keyteki#29]
Stun reads as follows: "When a creature becomes stunned, place a stun status card on it. The next time the creature is used, the only thing that happens is the creature exhausts and the stun card is removed. It does not reap or fight, and any “Reap:,” “Fight:,” or “Action:” abilities on the creature do not resolve. Constant abilities and abilities that do not require the creature to reap, fight, or be used are still active. If a stunned creature is attacked, it still deals damage to the attacking creature during the fight. While a creature is stunned, it cannot become stunned again.""

It doesn't matter how the creature is used, as long as it's used. Using would include attacking with it, reaping with it, or using an action printed on it. So my thinking would be since these cards allow you to ready and fight with a creature, fighting is a use, and so the creature is being used (to fight). Since it's being used (to fight), it would exhaust without fighting due to the stun, then lose the stun.

Thank you for reading. I apologize if this is already the case for most cards, I simply noticed it for "Follow the Leader" and assume it is the same in all similar instances.

**Comment by jeremylarner** [comment]
This should be fixed now

**Comment by DarthIA** [comment]
I just happened to use Anger having a stunned creature and it won't work :(
