### ISSUE TITLE
Pandemonium Bug

### ISSUE THREAD

**Issue by funshade** [jeremylarner/keyteki#3]
"Pandemonium Dis
Action
Aember: 1
Play: Each undamaged creature captures 1[AE] from its opponent.
Uncommon"
it's taking from the Creature's owners pool instead of the creature's opponent's pool

**Comment by Eric-Fletcher** [comment]
Also, Pandemonium should prompt the active player for which creatures do the capturing, if there are more creatures than aember available.

**Comment by jeremylarner** [comment]
This should be fixed now
