### ISSUE TITLE
Sneklifter

### ISSUE THREAD

**Issue by svenz1** [jeremylarner/keyteki#30]
I've used Sneklifter for steal an artifact from my opponent (Logos).
The artifact don't belong to one of my 3 houses.
The artifatc remain Logos and is impossibile use it n my turn.
Thanks

**Comment by svenz1** [comment]
The text of the card says: Take control of an enemy artifact. While under your control, if it does not belong to one of your three houses, it is considered to be of house Shadows.
The house is Shadows but i can use the card calling Logos?

**Comment by myrrien** [comment]
my bed, I had it confused with another card, it should in fact be
considered Shadows

**Comment by svenz1** [comment]
How resolve this problem in thecrucible.online?
Can i use the manual mode for use the artifact in the shadows turn?

**Comment by myrrien** [comment]
you should use manual mode to apply the effects of the artifact

**Comment by jeremylarner** [comment]
This should be fixed now
