### ISSUE TITLE
Chota Hazri - Do not do the requested action

### ISSUE THREAD

**Issue by soufiensky** [jeremylarner/keyteki#311]
When I play "Chota Hazri" it makes me lose 1 amber but the key is not forged as shown on the card.

**Comment by MooDySmiles** [comment]
Did you have the necessary amount of aember in your pool after the effetcs of "Chota Hazri" was applied?
Remember, "Chota Hazri" makes you lose 1 aember as soon as he is put on the field, then the check on the possibility to forge the key is done! (This means you need 7 aember -on normal cases- to forge a key with "Chota Hazri")

**Comment by soufiensky** [comment]
Ok, I did not understand the card application that way.
Thank you
