### ISSUE TITLE
Calo Phantom - No action

### ISSUE THREAD

**Issue by soufiensky** [jeremylarner/keyteki#312]
Carlo Phantom does not do the requested action "Each time you play an artifact steal 1 amber". Nothing happens !!

**Comment by MooDySmiles** [comment]
Could you be a little more precise on the circumstances in which you had Carlo Phantom on the field and his effects did not applied?

Did you play the artifact from the hand, or did you activate it? (It's easier for the developers to reproduce the scenario in order to fix it :) )

**Comment by soufiensky** [comment]
When Carlo Phantom is in the field ready to use, I activate an artifact ready to use on the field (either from the same house or from another house), but at that moment, I do not recover the amber.

**Comment by MooDySmiles** [comment]
Well, I guess you answered yourself! 🚀 

Carlo Phantom steals 1 aember when you play an artifact from your hand, not when you use one.

Veylan Analyst allows you to gain 1 aember when you use an artifact, not Carlo Phantom.

**Comment by soufiensky** [comment]
Ok 
I understand better
thanks again
