### ISSUE TITLE
Unable to verify account

### ISSUE THREAD

**Issue by mortis316uk** [jeremylarner/keyteki#36]
registered this evening but no email to verify account showing therefore can't login

**Comment by rdblanch** [comment]
I had the same problem.

**Comment by jeremylarner** [comment]
Check your spam folder

**Comment by ChampAnaphiel** [comment]
Same problem, spam folder check but nothing. I’ve tried to create an account with 2 different email but not one of them receive any email from the crucible site.

**Comment by rdblanch** [comment]
I checked mine too. Nothing.

**Comment by jeremylarner** [comment]
Unfortunately, I'm having some issues with the email provider we're using, especially for hotmail, outlook and yahoo accounts.  If you contact me on the Discord (link is on the Community page on the site), I can verify your account manually

**Comment by rdblanch** [comment]
Thanks. Will do.
