### ISSUE TITLE
Bear Flute - Not allowing you to search library

### ISSUE THREAD

**Issue by Mahipar** [jeremylarner/keyteki#37]
It seems like Bear Flute is not letting you search your deck for bears. I have now experienced this twice where I played the flute turn 1 and then on turn 2 attempted to use the flute. The prompt came up asking me to choose the creatures but it did not open a window to allow me to search my deck. When I clicked show on my deck an empty window popped up.

**Comment by Mahipar** [comment]
No player had a bear in play fyi

**Comment by mathemagician83** [comment]
deck searching mechanics appear to be broken...had the same problem with Bear Flute not allowing me to search my deck as well as Help from Future Self not allowing deck searching for Timetraveler.

**Comment by jeremylarner** [comment]
This should be fixed now
