### ISSUE TITLE
Combat pheromones

### ISSUE THREAD

**Issue by AvrilPL** [jeremylarner/keyteki#39]
Using this card triggered info in chat that it will allow using 2 Mars cards but I had to switch to Mars house manually to do that.

**Comment by blinkingline** [comment]
Not sure if this is relevant, but Combat Pheromones allows you to USE (Reap, Fight, Action) Mars cards, but not PLAY Mars cards. Did you have ready Mars cards available to be used?

**Comment by AvrilPL** [comment]
Sweet mother of god you are right... 🤕
