### ISSUE TITLE
When Ember Imp is taken over, the card limit doesn't switch. 

### ISSUE THREAD

**Issue by blinkingline** [jeremylarner/keyteki#4]
In a recent game, opponent took control of Ember Imp (dis) through Harland Mindlock (logos). The card moved to my opponent, but Ember Imp's restriction did not lift from opponent, nor did it apply to me on subsequent turns.

**Comment by funshade** [comment]
This happens with all "take over" minions tbh. the Dis card "select a house, that house cant be used" card aslo does not switch over.

**Comment by jeremylarner** [comment]
This should be fixed now
