### ISSUE TITLE
Mavericks

### ISSUE THREAD

**Issue by Tilbo** [jeremylarner/keyteki#401]
Maverick cards are just showing the broken image logo. I only have one so can't test to see if this affects all across the board. Card in question was Lamindra under the Untamed house.
(using Firefox)

**Comment by romanogit** [comment]
Do you have the deck name?
I worked on #147 so something mighr be wrong

**Comment by 4ugeistr** [comment]
2019-07-31 - Maverick cards should now have images
Please retest.

**Comment by Tilbo** [comment]
Yes, it works. Thank you.

**Comment by 4ugeistr** [comment]
![image](https://user-images.githubusercontent.com/23107141/62363549-43a95180-b528-11e9-816d-8f8459355360.png)
Can you close the issue then? ;)

**Comment by Tilbo** [comment]
Apologies.
Now closed.
