### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by Slugfairy** [jeremylarner/keyteki#41]
Been trying to login.
Used various browsers.
I have registered, however when I attempt to sign in, one of two things happens:
1. Invalid Username/password message
2. Need to validate email before logging in.

I have not received an email and I even re-registered under a different name and it still did not work.
Cheers.

**Comment by jeremylarner** [comment]
check your spam filter for email - they're definitely working.  If you can join the discord and PM me, I can check your account details

**Comment by ghost** [comment]
I'm having the same issue - trying to login with an account i know works and has been validated in the past and its throwing a 'Invalid username/password' message

**Comment by ChampAnaphiel** [comment]
Same problem no email received.

**Comment by Antux09** [comment]
Same issue here 👎 what is the discord?

**Comment by jeremylarner** [comment]
Unfortunately, I'm having some issues with the email provider we're using, especially for hotmail, outlook and yahoo accounts.  If you contact me on the Discord (link is on the Community page on the site), I can verify your account manually

**Comment by YogScott** [comment]
Same problem; cannot log in, cannot reset my password as no email is received.  I've checked my spam filters in case the emails got routed into there.
