### ISSUE TITLE
Email to verify account  has not come through 

### ISSUE THREAD

**Issue by toastiertree** [jeremylarner/keyteki#43]
I have checked all my emails folders including spam it has not come through on any of them I use outlook if that helps

**Comment by SnappedCoffee** [comment]
Same issue here. Futhermore, password recovery is not possible, because the captcha is broken.
I checked the spam folder and there is no verification mail in it.

**Comment by ChampAnaphiel** [comment]
Same problem and I’ve tried with different email accounts. I’ve check everywhere in my emails, being waiting over an hour. No confirmation email or activation email.

**Comment by midmad** [comment]
Same issue. I’ve been waiting 2days.

**Comment by Psychelics** [comment]
Tried 3 different emails services but I have gotten no verification link. Please fix it I wanna try out the game! >D

**Comment by Dirtmonk3y** [comment]
Im in the same boat. :/

**Comment by jeremylarner** [comment]
Unfortunately, I'm having some issues with the email provider we're using, especially for hotmail, outlook and yahoo accounts.  If you contact me on the Discord (link is on the Community page on the site), I can verify your account manually

**Comment by Dirtmonk3y** [comment]
It has come through, all good thank you very much for following up.

**Comment by ChampAnaphiel** [comment]
> Unfortunately, I'm having some issues with the email provider we're using, especially for hotmail, outlook and yahoo accounts. If you contact me on the Discord (link is on the Community page on the site), I can verify your account manually

Trying to find the link to contact you. Can’t find it

**Comment by ChampAnaphiel** [comment]
Getting a bit complicated trying to contact you @jeremylarner does exist a simple way to doing it here or commenting the link here to all the people find the issue? So we can go straight to contact you from here untile you fix the problem..

**Comment by justinpierson** [comment]
No luck here, cant find the community tab...

**Comment by jeremylarner** [comment]
Community Tab is under Help on the website - cryo deleted it by accident I think....

**Comment by GiulioZa** [comment]
Same issue for me. No e-mail confirmation.

**Comment by Helerdril** [comment]
Me too, same problem with email verification. I'm using hotmail.

**Comment by Helerdril** [comment]
@jeremylarner what is your user on discord?

**Comment by jeremylarner** [comment]
Verification has now been disabled, so you should be able to log in. If you're still having issues, my handle on discord is Jadiel
