### ISSUE TITLE
Harland Mindlock

### ISSUE THREAD

**Issue by Jacksuhn** [jeremylarner/keyteki#47]
My opponent played Harland Mindlock against me, which captured a creature. The text states: "PLAY: Take control of an enemy flank creature until Harland Mindlock leaves play." I destroyed Harland Mindlock on my next turn but did not regain control of my creature. It stayed on my opponent's side of the board and neither of us were able to use the creature.

**Comment by jeremylarner** [comment]
I can't replicate this
