### ISSUE TITLE
War Chest

### ISSUE THREAD

**Issue by Jacksuhn** [jeremylarner/keyteki#48]
I was unable to activate War Chest because I had only one creature on the board and it was tapped. I played Gangar Chieftain which allows me to ready and fight with a neighboring creature, which automatically readied my one character and forced me to choose a fight target without allowing me to tap War Chest, which was ready from having played in a previous round. I should be able to activate the Chest even if I have no ready creatures since I may still be able to fight that round.

**Comment by fletcharama** [comment]
I also had War Chest which I should have been able to Action but couldn't

**Comment by chapel** [comment]
War chest can only be activated after you've killed from a fight. It isn't a persistent effect after activation like some of the other cards.

**Comment by jeremylarner** [comment]
I can't replicate an issue with The Warchest

**Comment by internetms52** [comment]
The War Chest not working.
Using action after enemy creature been killed didn't gain any ember.
