### ISSUE TITLE
Hysteria Cardimage is missing

### ISSUE THREAD

**Issue by Albireo20** [jeremylarner/keyteki#56]
Hello, the image for the shadows card "hysteria" is missing:

![unbenannt](https://user-images.githubusercontent.com/7295017/49096722-739ea780-f26b-11e8-8829-1b97080c52c8.png)

I already deleted and reimported the deck, but the image is still missing

**Comment by jeremylarner** [comment]
FFG haven't made maverick images available, so there's nothing I can do about this

**Comment by Albireo20** [comment]
ah ok thank you for the answer :)
