### ISSUE TITLE
The Warchest

### ISSUE THREAD

**Issue by lolazzaro** [jeremylarner/keyteki#7]
A couple of time I tried to use "the warchest" at the end of my turn but I could not select the card and use it's action.

**Comment by blinkingline** [comment]
Action: Gain 1[Æ] for each enemy creature that was destroyed in a fight this turn.

Note that enemy has to be destroyed by a fight to use this, if they are destroyed by non-fight damage, this doesn't apply.

**Comment by lolazzaro** [comment]
I know but it did not let me select the card, even if I can not score any points I should have been able to activate the card ability.

Today, I used it a couple more times: I managed to activate it but I got only 1 point even though I had destroyed 3 creatures (by fighting) each time.

If for everybody it is working fine, maybe I'm confuse or maybe it a bug of the deck (the countess of Windhedge).

**Comment by myrrien** [comment]
there's definitely an issue with the card, it is unselectable as if it were not a brobnar card (had to manual mode it)

**Comment by jeremylarner** [comment]
I can't replicate an issue with The Warchest
