### ISSUE TITLE
Brain Eater does not die after trading lethal damage in fight

### ISSUE THREAD

**Issue by Aragar199** [jeremylarner/keyteki#74]
https://keyforge-compendium.com/cards/137-Brain%20Eater

To reproduce:
Brain Eater attacks Rogue Ogre with captured Amber and trades 6 damage
Rogue Ogre is removed and returns captured Amber to opponent
Brain Eater procs draw a card for owner (not correct)
Brain Eater remains on board with lethal damage on the card (not correct)

**Comment by Eric-Fletcher** [comment]
The card draw is correct, given that it remained in play.

Was there anything in play boosting Brain Eater's Power?

**Comment by Aragar199** [comment]
No there was nothing boosting Brain Eater's Power.  It should not have remained in play to draw a card.

**Comment by jeremylarner** [comment]
I can't replicate this
