### ISSUE TITLE
Dis:  Soul snatcher not giving Aember properly

### ISSUE THREAD

**Issue by Dloaf** [jeremylarner/keyteki#76]
There have been a couple games where Soul Snatcher ends up giving both players aember for destroying creatures.

In one case it named me for gaining aember, gave me and the opponent aember.

Thanks for all that you do to keep the game going!

**Comment by jeremylarner** [comment]
This should be fixed now

**Comment by Dloaf** [comment]
Cheers, any plans for an 'undo' action, or picking a different house if you
made a mistake?

Awesome job.

**Comment by jeremylarner** [comment]
Undo is really hard to implement due to the way the game engine works.  You can pick a different house by typing /active-house dis in chat

**Comment by Dloaf** [comment]
Awesome, thanks
