### ISSUE TITLE
Key Hammer played turn 1 generated 6 amber for opponent

### ISSUE THREAD

**Issue by hebr3** [jeremylarner/keyteki#77]
I played Key Hammer on turn 1 going second.
The game generated 6 amber for my opponent and they were able to forge a key at the start of turn 2.

I have included the transcript of the match below
---
TheMelos is shuffling their deck
heb3 is shuffling their deck
 heb3 has connected to the game server
 TheMelos has connected to the game server
heb3
Hello, good luck
TheMelos
hi gl
Key phase - TheMelos - turn 1
TheMelos does not forge a key as they have 0  - current cost: 6 
House phase - TheMelos - turn 1
TheMelos chooses  as their active house this turn
Main phase - TheMelos - turn 1
TheMelos plays Mother
Ready phase - TheMelos - turn 1
TheMelos readies all their 
Draw phase - TheMelos - turn 1
TheMelos draws 1  up to their maximum hand size of 7
End of turn 1
TheMelos: 0  heb3: 0 
Turn 1
Key phase - heb3 - turn 1
heb3 does not forge a key as they have 0  - current cost: 6 
House phase - heb3 - turn 1
heb3 chooses  as their active house this turn
Main phase - heb3 - turn 1
heb3 plays Snudge
heb3 plays Mind Barb, gaining 1 
heb3 uses Mind Barb to discard a  at random
TheMelos discards Regrowth at random
heb3 plays Key Hammer, gaining 1 
heb3 uses Key Hammer to gain 6 
Ready phase - heb3 - turn 1
heb3 readies all their 
Draw phase - heb3 - turn 1
heb3 draws 3  up to their maximum hand size of 6
End of turn 1
TheMelos: 6  heb3: 2 
Turn 2
Key phase - TheMelos - turn 2
TheMelos forges a key, paying 6 
House phase - TheMelos - turn 2
 TheMelos has disconnected

**Comment by Eric-Fletcher** [comment]
This is the correct behavior. The 6 amber generation is not dependent on a key being unforged.
