### ISSUE TITLE
Wild Wormhole ISSUE

### ISSUE THREAD

**Issue by johnwhatt** [jeremylarner/keyteki#8]
This card sometimes does not play the next card from your deck like it should. but rather plays nothing instead and afterwards no more logos cards can be played from hand anymore either, eventhough it's still my turn and logos is active house, in those cases i can only end my turn, nothing more. it seems like this bug is triggered when the next card from the deck is not a logos card but any card from other house. hope this explanation helps.

**Comment by jeremylarner** [comment]
I can't replicate any issues with this card
