### ISSUE TITLE
Using Seeker Needle on a Bad Penny did not generate AEmber

### ISSUE THREAD

**Issue by mikelietz** [jeremylarner/keyteki#82]
I used Seeker Needle on my own Bad Penny. The card went back to my hand, as expected, but I did not get 1 aember too. There was nothing that would've modified this that I can remember being out.

**Comment by jeremylarner** [comment]
I can't replicate this

**Comment by mikelietz** [comment]
Looks like I can't replicate it either, now. The aember doesn't show up in the chat log, but I can confirm I had 1 after and 0 before.
