### ISSUE TITLE
Problems with Sneklifter and Combat Pheremones

### ISSUE THREAD

**Issue by unkulchered** [jeremylarner/keyteki#83]
Hey Jeremy,

First of all, you are awesome for making this platform for everyone to play keyforge. Truly amazing. 

I haven't had any luck with getting sneklifter to work -- I am able to get control of the enemy player's artifact, though if it isn't one of my own houses it should change to shadows, and it never does.

Also, for whatever reason I am always unable to use the omni ability on combat pheremones, I just click and it doesn't work. Using manual mode didn't allow me to activate it either.

Thanks again, it is so great to be able to play keyforge online!

**Comment by jeremylarner** [comment]
I can't replicate this
