### ISSUE TITLE
Pile of Skulls interrupts and ends Cooperative Hunting

### ISSUE THREAD

**Issue by vicivc** [jeremylarner/keyteki#84]
I used Cooperative Hunting with Pile of Skulls in play to allocate 8 points of damage on enemy creatures.  After my fourth damage placed, I destroyed an enemy creature which caused Pile of Skulls to activate.  After I selected my minion to place the captured aember on, both effects ended, and I couldn't allocate the rest of my damage.

**Comment by jeremylarner** [comment]
This should be fixed now
