### ISSUE TITLE
Gauntlet of Command allowing reap

### ISSUE THREAD

**Issue by zbiggety** [jeremylarner/keyteki#86]
Gauntlet of Command says "Action: Ready and fight with a friendly creature. (That creature may be from any house.)". When gauntlet of command is used, it is readying a creature but it allows you to reap with the creature instead of just being limited to fighting.

**Comment by ira212** [comment]
This isn't a bug, assuming your opponent has no creatures to fight, and the creature you readied is in Brobnar.

**Comment by zbiggety** [comment]
Some cards allow you to "ready and use" a friendly creature, in which case you could choose what action to take. This one specifically says "ready and fight with". Why would you be able to do anything else but fight?

**Comment by myrrien** [comment]
if the opponent has no creatures, you only ready the selected creature, which can then be used to reap if it's of the active house

**Comment by zbiggety** [comment]
Why would you be able to reap with it just because the opponent has no creatures? It doesn't say ready and use, it says ready and fight. The wording on a lot of Brobnar cards is specifically about fighting instead of using. If you can't fight with the creature, then nothing should happen

**Comment by myrrien** [comment]
From the rules, you do as much of the text of a card as possible, so if the opponent has no creatures you just ready the target creature. If that creature is in Brobnar house then being ready it can be used for reaping.

**Comment by zbiggety** [comment]
Ok that's fair, I understand the interaction. It just looked like they were being used right away
