### ISSUE TITLE
Choose A House Cards Issues

### ISSUE THREAD

**Issue by Dyricos** [jeremylarner/keyteki#87]
Whenever I play a card from any of my decks that says "choose a house..." whenever it comes to choosing a house the houses in the options are sometimes random and not the ones that I or my opponent are using. This has caused several issues in a few of the games I have played including the latest one where I played Blinding Light to stun my opponents Mars creatures, but Mars was not one of the options for the houses of my opponent so I could not stun anything making me waste that action and making my opponents creatures able to attack/reap the next turn!

**Comment by jeremylarner** [comment]
You should be able to scroll down on the house prompt
