### ISSUE TITLE
problem with Sneklifter + The Sting

### ISSUE THREAD

**Issue by BrickSpirou** [jeremylarner/keyteki#90]
Hello Jeremy, 

Reporting what seems to be an issue with "Sneklifter"and "The Sting".

My opponent has "The Sting" in play and 6 aembers
I have 7 aembers and play "Sneklifter" on my turn stealing "The Sting".

On his next turn, my opponent can now forge a key for 6, but instead of me gaining the used aembers because i control "The Sting", he gets his aembers back, so he forge his key, he is still at 6 aembers and me at 7 instead of 0 form him and 13 for me.

Hope this help to improve this already good implementation of  keyforge.

**Comment by jeremylarner** [comment]
This should be fixed now
