### ISSUE TITLE
Combat Pheromones doesn't allow repeat uses of the same card as it should

### ISSUE THREAD

**Issue by neffmallon** [jeremylarner/keyteki#95]
Combat Pheromones allows the player to use two mars cards, but doesn't limit how often you can use them. For example, "John Smyth" allows you to re-ready a friendly mars creature, so using a Mars creature, then reaping with "John Smyth" (preparing that creature again) and then using that creature again should be allowed, but it isn't. Also, since order can matter, the player should be able to use the two Mars cards at any point during their turn, not just right after they have sacrificed Combat Pheromones.

**Comment by jeremylarner** [comment]
Do you have a ruling saying that you should be able to use 2 Mars cards several times?  If so, I can change it

**Comment by neffmallon** [comment]
I emailed sent an e-mail to FFG:
> Combat Pheromones (Artifact): Omni: Sacrifice Combat Pheromones. You may use up to 2 other Mars cards this turn.
> There is a lot of debate about what this card allows online, e.g. [https://www.reddit.com/r/KeyforgeGame/comments/9zjwxo/combat_pheromones_ruling/](https://www.reddit.com/r/KeyforgeGame/comments/9zjwxo/combat_pheromones_ruling/)
> Does Combat Pheromones allow two card uses or otherwise legal unlimited use of two specific cards? For example, can I reap with a non-agent Mars creature, reap with John Smyth to re-prepare that same Mars creature, then reap with that same Mars Creature again since only two physical cards are used? Or do you only get two card uses (meaning this chain does not work)?

And I got this response:

> Hi Nathan,
> In particular Combat Phermones is granting permission to use a creature [sic] during that turn. If you have an effect that readies one of the Mars cards affected by the Combat Pheromones (Such as John Smyth), you will be able to use that card again.
> Hope that helps!
> 
> Brad A.
> Card Game Developer
> Fantasy Flight Games
> [email redacted]
